name: thenexstore
description: "E-commerce app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.



  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.5
  image_picker: ^1.0.7
  permission_handler:
  provider: ^6.0.2
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  intl: 0.19.0
  pinput: ^5.0.0
  smart_auth: ^3.2.0

  speech_to_text: ^7.0.0
  path_provider:
  flutter_html:
  device_info_plus:
  freezed_annotation: ^2.4.4
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.1
  google_maps_flutter: ^2.13.1
  geolocator: ^10.1.0
  razorpay_flutter: ^1.4.0
  url_launcher: ^6.3.1
  firebase_core:
  firebase_notifications_handler: ^2.0.2+1


dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 800
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 400


